# Copyright (C) 2025-2026  Henrique Almeida
# This file is part of h3nc4-compose.
#
# h3nc4-compose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# h3nc4-compose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with h3nc4-compose.  If not, see <https://www.gnu.org/licenses/>.

name: h3nc4-compose

networks:
  exposed:
    name: exposed
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"

  external:
    name: external
    driver: bridge
    internal: false

  internal:
    name: internal
    driver: bridge
    internal: true

services:
  dns:
    container_name: dns
    image: coredns/coredns:1.14.2@sha256:e7e6440cfd1e919280958f5b5a6ab2b184d385bba774c12ad2a9e1e4183f90d9
    restart: always
    command: -conf /config/Corefile
    read_only: true
    profiles:
      - production
    ports:
      - "0.0.0.0:53:53/udp"
      - "0.0.0.0:53:53/tcp"
    cap_drop:
      - NET_RAW
      - MKNOD
      - SYS_MODULE
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/coredns/Corefile:/config/Corefile:ro
      - ./config/coredns/blocklist.hosts:/config/blocklist.hosts:ro
    networks:
      - internal
      - exposed

  maddy:
    image: foxcpp/maddy:0.8@sha256:eeb5813fc4d101ec5d8f7b08b7255fd76ced2a06884ea94450c8a9a22fd6a08d
    container_name: maddy
    restart: always
    environment:
      - MADDY_HOSTNAME=${MADDY_HOSTNAME}
      - MADDY_DOMAIN=${MADDY_DOMAIN}
      - SMTP_RELAY_HOST=${SMTP_RELAY_HOST}
      - SMTP_RELAY_USER=${SMTP_RELAY_USER}
      - SMTP_RELAY_PASSWORD=${SMTP_RELAY_PASSWORD}
    ports:
      - "[::]:25:25" # SMTP
      - "[::]:587:587" # Submission
      - "[::]:993:993" # IMAP
    volumes:
      - ./data/maddy:/data
      - ./config/maddy/maddy.conf:/data/maddy.conf
      - ./data/certbot/certs/:/etc/letsencrypt/
    networks:
      - internal
      - exposed

  tddns:
    container_name: tddns
    image: h3nc4/tddns@sha256:da8bb2facc2ddd5febc6aaf446a9b22ca148152931712e6d8fa2a71d89c817e0
    restart: always
    profiles:
      - production
    network_mode: "host"
    environment:
      - CF_TOKEN=${CF_TOKEN}
      - DOMAIN=${DOMAIN}
      - RECORD_TYPE=${RECORD_TYPE}
    volumes:
      - ./data/tddns:/var/run
    cap_drop:
      - ALL

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    restart: always
    profiles:
      - production
    read_only: true
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./config/cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    networks:
      - internal
      - external

  h3nc4:
    container_name: h3nc4
    domainname: h3nc4.com
    image: h3nc4/portfolio@sha256:ff5ec082693070bc3321c9a7a6967bfa04fcf50a7b1f08cb43f14796e3069eae
    restart: always
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

  wasudoku:
    container_name: wasudoku
    hostname: wasudoku
    domainname: h3nc4.com
    image: h3nc4/wasudoku@sha256:a86297e567767850ade2f97ad9236723f6764b87b971ca9e21f0533c20f49077
    restart: always
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

  cgit:
    container_name: cgit
    image: h3nc4/cgit-slim@sha256:8a07903c2e8bc7881c905d16f4a0e59a8d0bb2e8c3a3c289c26f1b5be57ec2a9
    restart: always
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/cgit/repos.list:/etc/cgit/repos.list:ro
      - ./data/cgit/git:/var/lib/git
      - ./data/cgit/ssh/id_ed25519:/run/.ssh/id_ed25519
      - ./data/cgit/ssh/id_ed25519.pub:/run/.ssh/id_ed25519.pub
    extra_hosts:
      - "github.com:4.228.31.150"
    networks:
      - internal
      - external

  tor:
    container_name: tor
    image: h3nc4/tor-slim@sha256:a5220411cf08d65390a90112fcf78f32f809979ab7b12f7dd6bff581e2538aef
    restart: always
    profiles:
      - production
    read_only: true
    user: "65534:65534"
    ports:
      - "0.0.0.0:9050:9050/tcp"
    cap_drop:
      - ALL
      - MKNOD
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/tor/torrc:/etc/tor/torrc:ro
      - ./data/tor:/var/lib/tor
    networks:
      - internal
      - external

  tor-reverse-proxy:
    container_name: tor-reverse-proxy
    image: h3nc4/nginx-slim@sha256:e94557515c87f4597502e76c594d4e675125a9331f8b279bba0a9eb44520c98e
    restart: always
    volumes:
      - ./config/tor/nginx.conf:/etc/nginx.conf:ro
    networks:
      - internal

  telegram-scout:
    container_name: telegram-scout
    image: h3nc4/telegram-scout@sha256:618d920aabdb103fc08d5492aff9b2082496659ee726c8c6e07760c5892856d9
    restart: always
    profiles:
      - production
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_PASSWORD=${TELEGRAM_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_SESSION=${TELEGRAM_SESSION}
    volumes:
      - ./config/telegram-scout/config.yaml:/config.yaml:ro
    networks:
      - external

  wireguard:
    container_name: wireguard
    image: codeberg.org/wg-easy/wg-easy:15@sha256:cf815209439101842f81d62bb25f7d66140e4cf8c100b4de5d0e84569d38732a
    network_mode: 'host'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    environment:
      - INSECURE=true

  minecraft:
    container_name: minecraft
    image: h3nc4/minecraft-slim:latest@sha256:ed444551a91f8eb32988e22b9e258d4779d511bb4f55f18326373496140cd259
    restart: unless-stopped
    stdin_open: true
    tty: true
    profiles:
      - production
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - ./data/minecraft:/data
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  syshealthcheck:
    container_name: syshealthcheck
    image: busybox:musl@sha256:19b646668802469d968a05342a601e78da4322a414a7c09b1c9ee25165042138
    volumes:
      - ./test.sh:/test.sh:ro
    command: /test.sh
    environment:
      - CI=${CI:-false}
    healthcheck:
      test: [ "CMD", "test", "-f", "/healthy" ]
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 1s
    depends_on:
      - maddy
      - cgit
      - h3nc4
      - wasudoku
      - tor-reverse-proxy
    networks:
      - internal
